name: altura_pos
description: "Offline-First POS System for F&B businesses"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  
  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  
  # Local Database
  drift: ^2.22.0
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.5
  path: ^1.9.0
  
  # Network & HTTP
  dio: ^5.7.0
  connectivity_plus: ^6.1.1
  
  # Background Tasks
  # workmanager: ^0.5.2  # Temporarily disabled due to compatibility issues
  
  # Data Serialization
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  
  # Storage
  shared_preferences: ^2.3.3
  flutter_secure_storage: ^9.2.2
  
  # Utilities
  intl: ^0.20.1
  uuid: ^4.5.1
  encrypt: ^5.0.3
  crypto: ^3.0.3
  
  # PDF & Printing
  pdf: ^3.11.1
  printing: ^5.13.4
  share_plus: ^10.1.3
  
  # Charts
  fl_chart: ^0.69.2
  
  # Functional Programming
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.13
  drift_dev: ^2.22.0
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  # riverpod_generator: ^2.6.2  # Temporarily disabled due to analyzer compatibility
  # riverpod_lint: ^2.3.13  # Temporarily disabled
  # custom_lint: ^0.7.3  # Temporarily disabled

flutter:
  uses-material-design: true
